version: "3.8"
services:
    first:
        image: user-manager:latest
        ports:
            - 5050:3000
        deploy:
            replicas: 3
    second:
        image: user-manager:latest
        ports:
            - 5050:3001
        deploy:
            replicas: 2
